### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by WeshGuillaume** [8-I/Voyager#1]
- [ ] Prevent window drag n drop when dragging a tabulation: should be fix when implementing tabs-drag'n'drop
- [ ] Create a localhost extension ???
- [x] Refactor Github branches and process
- [ ] Context handlers
  - [ ] Copy / Paste
  - [ ] Search on the web
  - [ ] Exec query
- [ ] implement find-on-page
- [ ] Create native home page `voyager:home`
- [ ] Create Settings page `voyager://settings`
- [ ] Create extensions manager `voyager://extensions`
- [ ] Create Extension Boilerplate `voyager://extensions/create`
- [ ] Create Error page `This page does not exists`
- [ ] Create Crash page
- [x] Fix cmd+L maybe focus an other input
- [ ] Can double click on topbar to toggle fullscreen
- [ ] voyager://history screen
- [ ] reopen last tabs
- [ ] Create a database for the history
- [x] Fix shortcuts i.e cmd+w
- [x] Refactor the code in a more comprehensive way
- [ ] Comment
- [ ] Cmd+shift+T
- [ ] implement all the [webview events](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md)
- [ ] redesign the tabs to make the active tab more visible
- [ ] create a like and bookmark middleware
  - [ ] link them with the address buttons
- [ ] Create a config/settings page
- [ ] Store the shortcuts in a JSON file
# Actions
- [x] pushTab : push a tab to the state
- [x] setCurrent : set the current tab
- [x] selectInput : select the current input
- [x] deleteIndex : delete a tab at index i
- [x] addTab : add a new tab
  - [x] pushTab
- [x] RemoveTab
  - [x] deleteIndex
  - [x] setCurrent
- [ ] Redesign the default alert/confirm/prompt windows

**Comment by GuillaumeBadi** [comment]
- [ ] Create native home page `voyager:home`
 - [ ] Create Settings page `voyager://settings`
 - [ ] Create extensions manager `voyager://extensions`
 - [ ] Create Extension Boilerplate `voyager://extensions/create`
 - [ ] Create Error page `This page does not exists`

**Comment by nbeydoon** [comment]
- [ ] Fix cmd+L maybe focus an other input
 - [ ] Can double click on topbar to toggle fullscreen
 - [ ] voyager://history screen
 - [ ] reopen last tabs

**Comment by GuillaumeBadi** [comment]
- [ ] Create a database for the history

**Comment by GuillaumeBadi** [comment]
- [ ] Refactor the code in a more comprehensive way
 - [ ] Comment

**Comment by nbeydoon** [comment]
- [ ] sound icon

**Comment by GuillaumeBadi** [comment]
# Actions

 - [ ] pushTab : push a tab to the state
 - [ ] setCurrent : set the current tab
 - [ ] selectInput : select the current input
 - [ ] deleteIndex : delete a tab at index i

 - [ ] addTab : add a new tab
  - [ ] pushTab

 - [ ] RemoveTab
   - [ ] deleteIndex
   - [ ] setCurrent

**Comment by nbeydoon** [comment]
- [] cannot select text in webview

**Comment by GuillaumeBadi** [comment]
- [ ] implement all the [webview events](https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md) here
 - [ ] redesign the tabs to make the active tab more visible
 - [ ] create a like and bookmark middleware
  - [ ] link them with the address buttons

- [ ] Create a config/settings page
- [ ] Store the shortcuts in a JSON file
